In [1]:
import pandas as pd

In [2]:
df=pd.read_csv(
"/content/sample_data/IMDB Dataset.csv",
                encoding="utf-8",
                engine = 'python',
                on_bad_lines='skip'
)
df

                                                 review sentiment
0     One of the other reviewers has mentioned that ...  positive
1     A wonderful little production. <br /><br />The...  positive
2     I thought this was a wonderful way to spend ti...  positive
3     Basically there's a family where a little boy ...  negative
4     Petter Mattei's "Love in the Time of Money" is...  positive
...                                                 ...       ...
3975  Visually cluttered, plot less, incredibly mind...  negative
3976  OK,so this film is NOT very well known,and was...  positive
3977  Reeves plays Haji Murad, a hero in 1850's Russ...  negative
3978  My brother-in-law and his wife brought the mov...  negative
3979  Now, I'm a big fan of Zombie movies. I admit Z...  negative

[3980 rows x 2 columns]

In [3]:
df.columns

Index(['review', 'sentiment'], dtype='object')

In [4]:
df["review"][2].lower()

'i thought this was a wonderful way to spend time on a too hot summer weekend, sitting in the air conditioned theater and watching a light-hearted comedy. the plot is simplistic, but the dialogue is witty and the characters are likable (even the well bread suspected serial killer). while some may be disappointed when they realize this is not match point 2: risk addiction, i thought it was proof that woody allen is still fully in control of the style many of us have grown to love.<br /><br />this was the most i\'d laughed at one of woody\'s comedies in years (dare i say a decade?). while i\'ve never been impressed with scarlet johanson, in this she managed to tone down her "sexy" image and jumped right into a average, but spirited young woman.<br /><br />this may not be the crown jewel of his career, but it was wittier than "devil wears prada" and more interesting than "superman" a great comedy to go see with friends.'

In [5]:
df['review']=df['review'].str.lower()

In [6]:
df['review']

0       one of the other reviewers has mentioned that ...
1       a wonderful little production. <br /><br />the...
2       i thought this was a wonderful way to spend ti...
3       basically there's a family where a little boy ...
4       petter mattei's "love in the time of money" is...
                              ...
3975    visually cluttered, plot less, incredibly mind...
3976    ok,so this film is not very well known,and was...
3977    reeves plays haji murad, a hero in 1850's russ...
3978    my brother-in-law and his wife brought the mov...
3979    now, i'm a big fan of zombie movies. i admit z...
Name: review, Length: 3980, dtype: object

## Remove HTML Tag

In [7]:
import re

In [8]:
def remove_html(text):
  pattern=re.compile('<.*?>')
  return pattern.sub(r'',text)

In [9]:
remove_html(df['review'][2])

'i thought this was a wonderful way to spend time on a too hot summer weekend, sitting in the air conditioned theater and watching a light-hearted comedy. the plot is simplistic, but the dialogue is witty and the characters are likable (even the well bread suspected serial killer). while some may be disappointed when they realize this is not match point 2: risk addiction, i thought it was proof that woody allen is still fully in control of the style many of us have grown to love.this was the most i\'d laughed at one of woody\'s comedies in years (dare i say a decade?). while i\'ve never been impressed with scarlet johanson, in this she managed to tone down her "sexy" image and jumped right into a average, but spirited young woman.this may not be the crown jewel of his career, but it was wittier than "devil wears prada" and more interesting than "superman" a great comedy to go see with friends.'

In [10]:
text1= '''
Yesterday, I was exploring resources to learn Machine Learning and NLP. I found some excellent materials on https://phitron.io and also watched tutorials at https://www.youtube.com/watch?v=dQw4w9WgXcQ.

For research papers, I visited https://arxiv.org/abs/1706.03762 and read documentation from https://pytorch.org/docs/stable/index.html. One of my friends also shared a blog post available at www.medium.com/@ai_engineer/transformers-explained.

If you'd like to practice coding problems, check out https://leetcode.com/problemset/ or https://www.kaggle.com/datasets. These websites are very helpful for aspiring AI engineers.

'''

In [11]:
text1

"\nYesterday, I was exploring resources to learn Machine Learning and NLP. I found some excellent materials on https://phitron.io and also watched tutorials at https://www.youtube.com/watch?v=dQw4w9WgXcQ.\n\nFor research papers, I visited https://arxiv.org/abs/1706.03762 and read documentation from https://pytorch.org/docs/stable/index.html. One of my friends also shared a blog post available at www.medium.com/@ai_engineer/transformers-explained.\n\nIf you'd like to practice coding problems, check out https://leetcode.com/problemset/ or https://www.kaggle.com/datasets. These websites are very helpful for aspiring AI engineers.\n\n"

## Remove URL

In [12]:
def remove_url(text):
  pattern=re.compile(r"https?://\S+|www\.\S+")
  return pattern.sub('',text)

In [13]:
remove_url(text1)

"\nYesterday, I was exploring resources to learn Machine Learning and NLP. I found some excellent materials on  and also watched tutorials at \n\nFor research papers, I visited  and read documentation from  One of my friends also shared a blog post available at \n\nIf you'd like to practice coding problems, check out  or  These websites are very helpful for aspiring AI engineers.\n\n"

## Remove functuation

In [14]:
import string

In [15]:
exclude = string.punctuation

In [16]:
exclude

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [17]:
def remove_punc(text):
  for char in exclude:
    text = text.replace(char,"")

  return text

In [18]:
remove_punc("Hello this is Akash?!")

'Hello this is Akash'

In [19]:
def remove_punc1(text):
  return text.translate(str.maketrans(' ',' ',exclude))

In [20]:
remove_punc1("Helllo This is Akash exclusive?!")

'Helllo This is Akash exclusive'

In [21]:
chat_words = {
    "A3": "Anytime, Anywhere, Anyplace",
    "ADIH": "Another Day In Hell",
    "AFK": "Away From Keyboard",
    "AFAIK": "As Far As I Know",
    "ASAP": "As Soon As Possible",
    "ATK": "At The Keyboard",
    "ATM": "At The Moment",
    "BAE": "Before Anyone Else",
    "BAK": "Back At Keyboard",
    "BBL": "Be Back Later",
    "BBS": "Be Back Soon",
    "BFN": "Bye For Now",
    "B4N": "Bye For Now",
    "BRB": "Be Right Back",
    "BRUH": "Bro",
    "BRT": "Be Right There",
    "BSAAW": "Big Smile And A Wink",
    "BTW": "By The Way",
    "BWL": "Bursting With Laughter",
    "CSL": "Can’t Stop Laughing",
    "CU": "See You",
    "CUL8R": "See You Later",
    "CYA": "See You",
    "DM": "Direct Message",
    "FAQ": "Frequently Asked Questions",
    "FC": "Fingers Crossed",
    "FIMH": "Forever In My Heart",
    "FOMO": "Fear Of Missing Out",
    "FR": "For Real",
    "FWIW": "For What It's Worth",
    "FYP": "For You Page",
    "FYI": "For Your Information",
    "G9": "Genius",
    "GAL": "Get A Life",
    "GG": "Good Game",
    "GMTA": "Great Minds Think Alike",
    "GN": "Good Night",
    "GOAT": "Greatest Of All Time",
    "GR8": "Great!",
    "HBD": "Happy Birthday",
    "IC": "I See",
    "ICQ": "I Seek You",
    "IDC": "I Don’t Care",
    "IDK": "I Don't Know",
    "IFYP": "I Feel Your Pain",
    "ILU": "I Love You",
    "ILY": "I Love You",
    "IMHO": "In My Honest/Humble Opinion",
    "IMU": "I Miss You",
    "IMO": "In My Opinion",
    "IOW": "In Other Words",
    "IRL": "In Real Life",
    "IYKYK": "If You Know, You Know",
    "JK": "Just Kidding",
    "KISS": "Keep It Simple, Stupid",
    "L": "Loss",
    "L8R": "Later",
    "LDR": "Long Distance Relationship",
    "LMK": "Let Me Know",
    "LMAO": "Laughing My A** Off",
    "LOL": "Laughing Out Loud",
    "LTNS": "Long Time No See",
    "M8": "Mate",
    "MFW": "My Face When",
    "MID": "Mediocre",
    "MRW": "My Reaction When",
    "MTE": "My Thoughts Exactly",
    "NVM": "Never Mind",
    "NRN": "No Reply Necessary",
    "NPC": "Non-Player Character",
    "OIC": "Oh I See",
    "OP": "Overpowered",
    "POV": "Point Of View",
    "PRT": "Party",
    "PRW": "Parents Are Watching",
    "ROFL": "Rolling On The Floor Laughing",
    "ROFLOL": "Rolling On The Floor Laughing Out Loud",
    "ROTFLMAO": "Rolling On The Floor Laughing My A** Off",
    "RN": "Right Now",
    "SK8": "Skate",
    "SUS": "Suspicious",
    "TBH": "To Be Honest",
    "TFW": "That Feeling When",
    "THX": "Thank You",
    "TIME": "Tears In My Eyes",
    "TLDR": "Too Long, Didn’t Read",
    "TNTL": "Trying Not To Laugh",
    "TTFN": "Ta-Ta For Now!",
    "TTYL": "Talk To You Later",
    "U": "You",
    "U2": "You Too",
    "U4E": "Yours For Ever",
    "W": "Win",
    "W8": "Wait...",
    "WB": "Welcome Back",
    "WTG": "Way To Go!",
    "WUF": "Where Are You From?",
    "WYD": "What You Doing?",
    "WYWH": "Wish You Were Here",
    "ZZZ": "Sleeping, Bored, Tired",
    "OMG!": "Oh My God",
    "SMH": "Shaking My Head",
    "NGL": "Not Gonna Lie",
    "TBF": "To Be Fair",
    "ICYMI": "In Case You Missed It",
    "IMO": "In My Opinion",
    "IMHO": "In My Honest Opinion",
    "RN": "Right Now",
    "FR": "For Real",
    "DW": "Don't Worry",
    "ILYSM": "I Love You So Much",
    "OMW": "On My Way",
    "GGWP": "Good Game Well Played",
    "GG": "Good Game",
    "EZ": "Easy",
    "LMAO": "Laughing My A** Off",
    "LOL": "Laughing Out Loud"
}

In [22]:
def chat_conversion(text):
  new_text=[]

  for w in text.split():
    if w.upper() in chat_words:

      new_text.append(chat_words[w.upper()])
    else:

      new_text.append(w)
  return " ".join(new_text)

In [23]:
chat_conversion("AFK omg!")

'Away From Keyboard Oh My God'

## Spelling Correction

In [24]:
from textblob import TextBlob

In [25]:
incorrect_text = "helll this is Akash"

textblob=TextBlob(incorrect_text)

textblob.correct().string

'hell this is Wash'

## Stopwards Removal

In [26]:
text = """
Yesterday, I was working on a Machine Learning project in PHITRON, and I was trying to understand how the model is performing on the dataset. The dataset is quite large, and it contains a lot of reviews that are written by users from different countries.

I noticed that the model is not performing well for some of the samples, especially those that are very short or have too many stopwords in them. Because of this, I decided to clean the text data and remove unnecessary words that do not contribute much to the meaning of the sentence.

While I was doing this, I also checked how the preprocessing steps like tokenization, lowercasing, and punctuation removal are affecting the dataset. It was interesting to see that after removing stopwords, the text becomes more meaningful and easier for the model to understand.

In addition to that, I was also reading some documentation from https://scikit-learn.org/stable/ and watching tutorials on https://www.youtube.com while comparing different NLP techniques. The goal is to improve the accuracy of the model and make it more robust for real-world applications.

Overall, I think that removing stopwords is an important step in the NLP pipeline because it helps reduce noise and improve performance of machine learning models.
"""

In [27]:
import nltk

In [28]:
from nltk.corpus import stopwords

In [29]:
nltk.download("stopwords")

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

True

In [30]:
stop_words = set(stopwords.words('english'))

In [31]:
stop_words

{'a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 "he'd",
 "he'll",
 "he's",
 'her',
 'here',
 'hers',
 'herself',
 'him',
 'himself',
 'his',
 'how',
 'i',
 "i'd",
 "i'll",
 "i'm",
 "i've",
 'if',
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it'd",
 "it'll",
 "it's",
 'its',
 'itself',
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'only',
 'or',
 'other',
 'our',
 'ours',
 'ourselves',
 'out',
 'over',
 'own',
 're',
 's',
 'same',
 'shan',
 "shan't",
 'she',
 "she'd",
 "she'll",
 "she's",
 'should',
 "should've",
 'shouldn',
 "shouldn't",
 'so',
 'some',
 'such',
 't',
 'than',
 'that',
 "that'll",
 'the',
 'their',
 'theirs',
 'them',
 'themselves',
 'then',
 'there',
 'these',
 'they',
 "they'd",
 "they'll",
 "they're",
 "they've",
 'this',
 'those',
 'through',
 'to',
 'too',
 'under',
 'until',
 'up',
 've',
 'very',
 'was',
 'wasn',
 "wasn't",
 'we',
 "we'd",
 "we'll",
 "we're",
 "we've",
 'were',
 'weren',
 "weren't",
 'what',
 'when',
 'where',
 'which',
 'while',
 'who',
 'whom',
 'why',
 'will',
 'with',
 'won',
 "won't",
 'wouldn',
 "wouldn't",
 'y',
 'you',
 "you'd",
 "you'll",
 "you're",
 "you've",
 'your',
 'yours',
 'yourself',
 'yourselves'}

In [32]:
def stop_words_removal(text):
  words=text.split()
  cleaned=[]

  for word in words:

    word=word.lower().strip(string.punctuation)

    if word and word not in stop_words:
      cleaned.append(word)
  return ' '.join(cleaned)

In [33]:
stop_words_removal(text)

'yesterday working machine learning project phitron trying understand model performing dataset dataset quite large contains lot reviews written users different countries noticed model performing well samples especially short many stopwords decided clean text data remove unnecessary words contribute much meaning sentence also checked preprocessing steps like tokenization lowercasing punctuation removal affecting dataset interesting see removing stopwords text becomes meaningful easier model understand addition also reading documentation https://scikit-learn.org/stable watching tutorials https://www.youtube.com comparing different nlp techniques goal improve accuracy model make robust real-world applications overall think removing stopwords important step nlp pipeline helps reduce noise improve performance machine learning models'

In [34]:
df['review']=df['review'].apply(stop_words_removal)

In [35]:
df['review']

0       one reviewers mentioned watching 1 oz episode ...
1       wonderful little production br br filming tech...
2       thought wonderful way spend time hot summer we...
3       basically there's family little boy jake think...
4       petter mattei's love time money visually stunn...
                              ...
3975    visually cluttered plot less incredibly mind-n...
3976    ok,so film well known,and well publicised.i di...
3977    reeves plays haji murad hero 1850's russia.<br...
3978    brother-in-law wife brought movie one night wa...
3979    big fan zombie movies admit zombie movies usua...
Name: review, Length: 3980, dtype: object

## Emoji Removal

In [36]:
text_with_emoji = '''Yesterday I completed my Machine Learning project on sentiment analysis 😊🔥.
The model performed really well on the IMDB dataset 👍🎯.
I learned a lot about preprocessing steps like tokenization, stopwords removal, and stemming 📚💡.
However, debugging errors was quite frustrating 😓💻.
Overall, the experience was amazing and I feel more confident now 🚀😄.'''

In [37]:
import re

def remove_emoji(text):
    emoji_pattern = re.compile(
        "["
        "\U0001F600-\U0001F64F"  # emoticons
        "\U0001F300-\U0001F5FF"  # symbols & pictographs
        "\U0001F680-\U0001F6FF"  # transport & map symbols
        "\U0001F1E0-\U0001F1FF"  # flags
        "\U00002700-\U000027BF"  # dingbats
        "\U000024C2-\U0001F251"
        "]+",
        flags=re.UNICODE
    )
    return emoji_pattern.sub(r'', text)

In [38]:
clean_text = remove_emoji(text_with_emoji)
print(clean_text)

Yesterday I completed my Machine Learning project on sentiment analysis .
The model performed really well on the IMDB dataset .
I learned a lot about preprocessing steps like tokenization, stopwords removal, and stemming .
However, debugging errors was quite frustrating .
Overall, the experience was amazing and I feel more confident now .

## Tokenization

In [39]:
from nltk.tokenize import word_tokenize,sent_tokenize
import nltk

In [40]:
nltk.download('punkt')
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.

True

In [41]:
sent1 = 'I am going to visit Dhaka!'
word_tokenize(sent1)

['I', 'am', 'going', 'to', 'visit', 'Dhaka', '!']

In [42]:
text = """Lorem Ipsum is simply dummy text of the printing and typesetting industry?
Lorem Ipsum has been the industry's standard dummy text ever since the 1500s,
when an unknown printer took a galley of type and scrambled it to make a type specimen book."""

sent_tokenize(text)

['Lorem Ipsum is simply dummy text of the printing and typesetting industry?',
 "Lorem Ipsum has been the industry's standard dummy text ever since the 1500s,\nwhen an unknown printer took a galley of type and scrambled it to make a type specimen book."]

In [43]:
sent5 = 'I have a Ph.D in A.I'
sent6 = "We're here to help! mail us at nks@gmail.com"
sent7 = 'A 5km ride cost $10.50'

word_tokenize(sent7)

['A', '5km', 'ride', 'cost', '$', '10.50']

## Spacy

In [44]:
import spacy
nlp = spacy.load('en_core_web_sm')

In [45]:
doc1 = nlp(sent5)
doc2 = nlp(sent6)
doc3 = nlp(sent7)
doc4 = nlp(sent1)

In [46]:
for token in doc2:
    print(token)

We
're
here
to
help
!
mail
us
at
nks@gmail.com

## Steaming

In [47]:
from nltk.stem.porter import PorterStemmer

In [48]:
ps = PorterStemmer()

def stem_words(text):
    return " ".join([ps.stem(word) for word in text.split()])

In [49]:
sample = "walk walks walking walked"
stem_words(sample)

'walk walk walk walk'

In [50]:
text = 'probably my alltime favorite movie a story of selflessness sacrifice and dedication to a noble cause but its not preachy or boring it just never gets old despite my having seen it some 15 or more times in the last 25 years paul lukas performance brings tears to my eyes and bette davis in one of her very few truly sympathetic roles is a delight the kids are as grandma says more like dressedup midgets than children but that only makes them more fun to watch and the mothers slow awakening to whats happening in the world and under her own roof is believable and startling if i had a dozen thumbs theyd all be up for this movie'
print(text)

probably my alltime favorite movie a story of selflessness sacrifice and dedication to a noble cause but its not preachy or boring it just never gets old despite my having seen it some 15 or more times in the last 25 years paul lukas performance brings tears to my eyes and bette davis in one of her very few truly sympathetic roles is a delight the kids are as grandma says more like dressedup midgets than children but that only makes them more fun to watch and the mothers slow awakening to whats happening in the world and under her own roof is believable and startling if i had a dozen thumbs theyd all be up for this movie

In [51]:
stem_words(text)

'probabl my alltim favorit movi a stori of selfless sacrific and dedic to a nobl caus but it not preachi or bore it just never get old despit my have seen it some 15 or more time in the last 25 year paul luka perform bring tear to my eye and bett davi in one of her veri few truli sympathet role is a delight the kid are as grandma say more like dressedup midget than children but that onli make them more fun to watch and the mother slow awaken to what happen in the world and under her own roof is believ and startl if i had a dozen thumb theyd all be up for thi movi'

## Lemmitization

In [52]:
import nltk
from nltk.stem import WordNetLemmatizer

In [53]:
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to /root/nltk_data...

True

In [54]:
wordnet_lemmatizer = WordNetLemmatizer()

In [55]:
sentence = "He was running and eating at same time. He has bad habit of swimming after playing long hours in the Sun."

In [56]:
punctuations="?:!.,;"

In [57]:
sentence_words = nltk.word_tokenize(sentence)

In [58]:
for word in sentence_words:
    if word in punctuations:
        sentence_words.remove(word)

In [59]:
sentence_words

['He',
 'was',
 'running',
 'and',
 'eating',
 'at',
 'same',
 'time',
 'He',
 'has',
 'bad',
 'habit',
 'of',
 'swimming',
 'after',
 'playing',
 'long',
 'hours',
 'in',
 'the',
 'Sun']

In [60]:
for word in sentence_words:
    print ("{0:20}{1:20}".format(word,wordnet_lemmatizer.lemmatize(word,pos='v')))

He                  He
was                 be
running             run
and                 and
eating              eat
at                  at
same                same
time                time
He                  He
has                 have
bad                 bad
habit               habit
of                  of
swimming            swim
after               after
playing             play
long                long
hours               hours
in                  in
the                 the
Sun                 Sun